In [2]:
import numpy as np

In [3]:
"""
Problem Statement:
Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.
Output Format :
numpyArray
"""
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
"""
Problem Statement:
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.
Output Format :
element1 element2 element3 ... 
"""
(np.arange(10) == 4).view(np.uint8)


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

In [14]:
array = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype = int)

In [15]:
len(array)

10

In [16]:
np.random.randint(10, 4)

ValueError: low >= high

In [17]:
np.random.rand()

0.8551710581228856

In [19]:
"""
Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.
Output Format :
element1 element2 element3 ...
"""

np.arange(9, 50)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [20]:
"""
Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
Print the Numpy array.
Output Format :
numpyArray
"""
import numpy as np
ans = np.eye(5,6)
print(ans)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [36]:
"""
Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.
Output Format :
element1 
element2 
element3
.
.
"""

ans = np.linspace(0, 5, 9, )

for a in ans:
    print("{:.2f}m".format(a))

0.00m
0.62m
1.25m
1.88m
2.50m
3.12m
3.75m
4.38m
5.00m


In [37]:
"""
Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix
Alt Text Alt Text Alt Text Alt Text

Output Format :
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
"""
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

In [38]:
input_

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
print(input_[2, 0:3])
print(input_[1:, 3])
print(input_[2:, :])
print(input_[1:3, 1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


In [45]:
for i in input_[2, 0:3]:
    print(i, end=" ")
    


11 12 13 

In [46]:
for i in input_[1:, 3]:
    print(i, end=" ")

9 14 19 

In [56]:
for i in input_[2:, :]:
    for j in i:
        print(j, end=" ")
    

11 12 13 14 15 16 17 18 19 20 

In [57]:
for i in (input_[1:3, 1:3]):
    for j in i:
        print(j, end=" ")

7 8 12 13 

In [70]:
"""
Non-Zero elements
Send Feedback
Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :
index1 index2 index3 ... 
"""

arr = np.array([1,2,0,0,4,0], dtype = int)
arr[arr != 0]
ans = np.where(arr != 0)[0]
# print(ans)
print(*ans.tolist())

0 1 4


In [74]:
"""
Multiples of 3
Send Feedback
Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.
Output Format :
index1 index2 index3 ...
"""
arr = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype = int)
ans = np.where(arr % 3 == 0)[0]
for i in ans:
    print(i, end=" ")

1 4 7 

In [91]:
"""
Odd elements
Send Feedback
Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement secondElement  ... 
"""
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = int)
arr[(arr % 2 != 0)] = -1
print(*arr)

-1 2 -1 4 -1 6 -1 8 -1 10


In [111]:
"""
Replace Max
Send Feedback
Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.
Output Format :
firstElement
secondElement 
... 
"""
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19], dtype = int)
arr[arr.argmax()] = 0
for i in arr:
    print(i)

11
2
13
4
15
6
0
8
19


In [131]:
"""
Negate Elements
Send Feedback
Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement 
secondElement  
... 
"""

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [143]:
"""
Height
Send Feedback
Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.
Output Format :
age1 height1 
age2 height2 
... 
"""
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind = np.where(height > 155)

for i in ind[0]:
    print(age[i], height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [148]:
"""
Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]
"""

arr = np.array([[21, 20, 19, 18, 17],
  [16, 15, 14, 13, 12],
  [11, 10,  9,  8,  7],
  [ 6,  5,  4,  3,  2]])
arr[arr[:,1].argsort()]

In [155]:
arr[arr[:,1].argsort()]

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [147]:
arr

array([[17, 18, 19, 20, 21],
       [12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11],
       [ 2,  3,  4,  5,  6]])